# Generated by Django 4.2.8 on 2024-01-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='gshhhsh', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
